### ISSUE TITLE
Provision being called twice per claim

### ISSUE THREAD

**Issue by krancour** [deis/steward#163]
I'm 3 for 3 now in observing this.

Example claim:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: claim-1
  namespace: default
  labels:
    type: service-plan-claim
data:
  service-id: "postgresql"
  plan-id: "standard"
  claim-id: "asdasd7234213"
  action: "provision"
  target-name: "sample-result"
```

Logs:

https://gist.github.com/krancour/ca017347fe35f3aa293db0f0b777f7df
